# Generated by Django 3.2.9 on 2021-11-24 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='course_files')),
                ('title', models.CharField(max_length=300, null=True)),
                ('slug', models.SlugField(max_length=400)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('author', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
