# Generated by Django 3.2.9 on 2021-11-25 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Event_files')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('escription', models.TextField(null=True)),
                ('held_on', models.DateTimeField(null=True)),
                ('adress', models.CharField(max_length=200, null=True)),
                ('organisors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
