# Generated by Django 3.2.9 on 2021-11-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='escription',
            new_name='description',
        ),
    ]
