# Generated by Django 3.2.9 on 2021-11-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_escription_events_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='file',
            field=models.FileField(null=True, upload_to='application_files'),
        ),
    ]
