# Generated by Django 3.2.9 on 2021-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applications_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
