# Generated by Django 3.2.9 on 2021-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_applied',
        ),
        migrations.AddField(
            model_name='appliedcourse',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
