# Generated by Django 3.2.9 on 2021-12-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211130_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='adress',
            new_name='address',
        ),
    ]
