# Generated by Django 3.2.9 on 2021-12-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_adress_events_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Messagess',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
